### ISSUE TITLE
Installation and running this? 

### ISSUE THREAD

**Issue by zilveer** [therezor/laravel-transactional-jobs#1]
Hi
I am using the following code

`try {
    DB::beginTransaction();
    // database queries here
    DB::commit();
} catch (\PDOException $e) {
    // Woopsy
    DB::rollBack();
}`

In one of my controllers, how do I use this plugin so it can add the commits to the queue ?
Also I suppose that I need to enable latavel queue jobs , right ?

Can you please provide a step by step guide on how to make it work with laravel and what edits I need to make on laravel to make it work ?

Bear regards

**Comment by therezor** [comment]
Hi.
This package if for running laravel job after transaction successfully commits and skip if transaction fails.

Usage if fairly simple 
1. Replace BusServiceProvider using one from package.
2. Add porperty $afterTransactions = true to jobs that has to be run after transaction successfully commits.
 https://github.com/therezor/laravel-transactional-jobs/blob/master/README.md

**Comment by zilveer** [comment]
@therezor thx for your reply .
What is the main difference between the built in queue in Laravel and your plugin ?

**Comment by therezor** [comment]
It uses the same queue class but extended to prevent adding jobs to queue before data was actually saved to DB. That make it inaccessible inside workers job

**Comment by zilveer** [comment]
@therezor thanks, but what if the adding the job to DB fails, then we have data which has been saved to the DB?

**Comment by therezor** [comment]
If adding job to queue fails you'll have all your data committed to db.

**Comment by zilveer** [comment]
@therezor then the saved data, which has relationships to the jobs is failed as well. how is it possible to reverse this or really make sure that the jobs is actually added upon DB commit ?

**Comment by therezor** [comment]
![laravel way](https://user-images.githubusercontent.com/15324879/50332039-90946680-0509-11e9-91db-ccd2bc5c0ba1.jpeg)
![package way](https://user-images.githubusercontent.com/15324879/50332224-2cbe6d80-050a-11e9-8ccc-542d919560c3.jpeg)
