### ISSUE TITLE
Missing `.gitattributes` file

### ISSUE THREAD

**Issue by williamdes** [therezor/laravel-transactional-jobs#13]
Please provide a `.gitattributes` to remove useless files from production servers ;)

See: https://github.com/code-lts/Laravel-FCM/blob/main/.gitattributes

```tree
vendor/therezor/laravel-transactional-jobs
├── .circleci
│   └── config.yml
├── composer.json
├── .gitignore
├── img
│   ├── laravel_schema.jpeg
│   └── package_schema.jpeg
├── LICENSE
├── phpunit.xml
├── README.md
├── src
│   ├── BusServiceProvider.php
│   ├── Contracts
│   │   └── RunAfterTransaction.php
│   └── TransactionalDispatcher.php
└── tests
    └── TransactionalDispatcherTest.php


```

To be added in the file
- `/.circleci`
- `/.gitignore`
- `/.gitattributes`
- `/img`
- `/tests`
- `/phpunit.xml`

**Comment by therezor** [comment]
Thank you for your request. Solved

**Comment by williamdes** [comment]
Thanks you for https://github.com/therezor/laravel-transactional-jobs/commit/66ce180ae76f172aa2edb5556a6367efbae496af and this great lib!
