### ISSUE TITLE
Support for Laravel 10

### ISSUE THREAD

**Issue by stefanschindler** [therezor/laravel-transactional-jobs#18]
Hi!
It would be great if you could add support for Laravel 10 to this package.

Thanks!

**Comment by stefanschindler** [comment]
sorry!
I didn't see that the newest release already supports Laravel 10

**Comment by therezor** [comment]
Hi @stefanschindler It is supported by laravel 10, just for a compatibility. There is no reason to use it with laravel 10, as it is natively support this feature https://laravel.com/docs/10.x/queues#jobs-and-database-transactions
