### ISSUE TITLE
Is this project GPL or MIT ?

### ISSUE THREAD

**Issue by williamdes** [therezor/laravel-transactional-jobs#20]
https://github.com/therezor/laravel-transactional-jobs/blob/b262084abed32e62e14e650edf31e79e8147080c/composer.json#L5

The initial commit committed MIT ?
Would you say it is dual licenced ?

**Comment by therezor** [comment]
Thanks for reporting, it should be under MIT license as it is less restrictive

**Comment by williamdes** [comment]
Thank you!
https://github.com/therezor/laravel-transactional-jobs/releases/tag/1.1.5

Fixed by https://github.com/therezor/laravel-transactional-jobs/commit/855b1a3e64953a2142c20bcc5072373dd15eed26
