### ISSUE TITLE
Deprecation Notice for Composer v2.0

### ISSUE THREAD

**Issue by williamdes** [therezor/laravel-transactional-jobs#8]
- Deprecation Notice: Class:
TheRezor\TransactionalJobs\TransactionalDispatcher located in ./vendor/therezor/laravel-transactional-jobs/src/TransactionalDispatcher.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

- Deprecation Notice: Class:
TheRezor\TransactionalJobs\BusServiceProvider located in ./vendor/therezor/laravel-transactional-jobs/src/BusServiceProvider.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by therezor** [comment]
Thanks for report, will cover in new version

**Comment by therezor** [comment]
Should be fixed in v1.0
